### ISSUE TITLE
Add delay to StopTimeEvent

### ISSUE THREAD

**Issue by DomeQdev** [MKuranowski/WKDGTFS#1]
Docs: https://developers.google.com/transit/gtfs-realtime/reference#message-stoptimeevent

![image](https://user-images.githubusercontent.com/45435431/229136841-e95b14b5-efd7-4bf3-9597-92d64780dc51.png)

**Comment by MKuranowski** [comment]
From [the spec](https://gtfs.org/realtime/reference/#message-stoptimeevent):
> If both time and delay are specified, time will take precedence

[time is already provided](https://github.com/MKuranowski/WKDGTFS/blob/main/rt/wkd_rt.go#L779), so providing delay is redundant and makes no sense. Delay can be trivially reconstructed by subtracting the scheduled departure time from the realtime departure time.

---

Also, the scraper does not scrape the table you have attached, just the stop-based ones. Those don't have delay data.
